apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: mlops
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30851
      protocol: TCP
  selector:
    app: streamlit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: binhdang150802/mlops-streamlit:1.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: "http://api:8000"
            - name: MLFLOW_URL
              value: "http://mlflow:5000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"




